### ISSUE TITLE
Get Involved!

### ISSUE THREAD

**Issue by pedromtavares** [pedromtavares/moba#90]
Hey folks,

First of all thank you for showing interest in the project! Even though there is a good baseline already done, most of the work is still ahead of us, so it'll be a great learning opportunity for everyone.

The idea here is that I will develop an initial roadmap with some features and discuss them with you guys so that everyone gets a chance to work on something that is exciting for them. I'm also very open to ideas on how to improve the game, be it code-wise or feature-wise -- this is and always will be a community-driven project.

Feel free to comment on this issue introducing yourself, this way I'll have a better idea of how to plan the game's roadmap and  assign issues accordingly. For the time being, you can join our Discord at https://discord.gg/QNwEdPS, I'm always online and happy to discuss anything about the game, Elixir, or software engineering in general. 

Also, don't forget to play the game at https://browsermoba.com, game devs need to be good players ;)

**Comment by VPadmin2021** [comment]
Hello there, my name's Claire.

I came across Moba recently as I'm looking into building my own kind of game which focuses on the type of Character Development you'd get from Tabletop games.

I really love the game so far. It's simple and smooth, visually appealing, and the battle style is fun and rewarding. 
I'm surprised that there are no limitations on how many battles you can fight, like most games these days - particularly those in the mobile gaming market.  I also like that you can view your progress against other players.

**Comment by pedromtavares** [comment]
Hey Claire, great to have you around, hope you get some inspiration for your game by playing this one :)

In fact, for the initial game mode (Easy Mode) there isn't a limit on the amount of battles but on the "Veteran Mode", which is more competitive, there is. The idea is to measure your skill by how much you can farm, and there is an account progression system called the Season Quest that slowly boosts your effectiveness at farming along with making the game progressively harder (and more fun) to play.

I'm currently rethinking a few mechanics of leveling through the Jungle to make it even more appealing to new players and more competitive for older ones, hope you stick around to see that.

Cheers!
