### ISSUE TITLE
Not all popups are updated

### ISSUE THREAD

**Issue by Eiji7** [pedromtavares/moba#93]
Firstly noticed right after first fight and buying 2 things in shop:
![hp popup](https://user-images.githubusercontent.com/10956022/92026877-fd917380-ed61-11ea-9a28-03a485561c22.png)
![hp item popup](https://user-images.githubusercontent.com/10956022/92027425-d1c2bd80-ed62-11ea-8404-c44b7214edc5.png)

Please notice:
1. :heart: 351
2. Total HP: 335
3. Current base HP: 335
4. HP given by items: 0
5. :heart: +16 HP

Same goes here:
![armor popup](https://user-images.githubusercontent.com/10956022/92027793-51508c80-ed63-11ea-86b0-66e28ccd7495.png)
![armor item popup](https://user-images.githubusercontent.com/10956022/92027863-675e4d00-ed63-11ea-8958-797da4320735.png)

**Comment by pedromtavares** [comment]
Thank you for the clear report!

Definitely something around: https://github.com/pedromtavares/moba/blob/master/assets/js/app.js#L37 🤔 gonna poke a bit to see what happens.

**Comment by pedromtavares** [comment]
This one was annoying but has finally been fixed :)
